data:
	dd if=/dev/random of=sam4095.txt bs=4095 count=1
	dd if=/dev/random of=sam4096.txt bs=4096 count=1
	dd if=/dev/random of=sam4097.txt bs=4097 count=1
big:
	dd if=/dev/random of=samBig.txt bs=4096 count=20
