
PPWD:=$(shell pwd)

tool:
	make fileinfo
	make fraginfo


link:
	ln -s /home/mthakare/cs551os/prj_3/tool/fraginfo /usr/bin/fraginfo
	ln -s /home/mthakare/cs551os/prj_3/tool/fileinfo /usr/bin/fileinfo
